### ISSUE TITLE
Missing helpers.py module in wind_forecasting.run_scripts.helpers

### ISSUE THREAD

**Issue by boujuan** [achenry/wind-forecasting#35]
Couldn't find this script in the main or brach repository.

**Comment by achenry** [comment]
Where is this called? May not be needed anymore...

**Comment by boujuan** [comment]
> Where is this called? May not be needed anymore...

In the **run_model.py** script that you made,

`9 - from wind_forecasting.run_scripts.helpers import TorchDataModule`

**Comment by achenry** [comment]
I think that is the old run_model.py, check out the merge I just made into main
